sudo: required

services:
    - docker

before_install:
    - docker build -t sumanth/react-test -f ./client/Dockerfile.dev ./client

script: 'true'

after_success:
    - docker build -t sumanth/multi-client ./client
    - docker build -t sumanth/multi-nginx ./nginx
    - docker build -t sumanth/multi-server ./server
    - docker build -t sumanth/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker tag sumanth/multi-client:latest sumanth/multi-client:latest 
    - docker push sumanth/multi-client:latest
    - docker tag sumanth/multi-nginx:latest sumanth/multi-client:latest 
    - docker push sumanth/multi-nginx:latest
    - docker tag sumanth/multi-server:latest sumanth/multi-client:latest 
    - docker push sumanth/multi-server:latest
    - docker tag sumanth/multi-worker:latest sumanth/multi-client:latest 
    - docker push sumanth/multi-worker:latest





    