sudo: required

services:
    - docker

before_install:
    - docker build -t sumanth/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -it sumanth/react-test npm test -- --coverage

after_success:
    - docker build -t sumanth/multi-client ./client
    - docker build -t sumanth/multi-nginx ./nginx
    - docker build -t sumanth/multi-server ./server
    - docker build -t sumanth/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sumanth/multi-client
    - docker push sumanth/multi-nginx
    - docker push sumanth/multi-server
    - docker push sumanth/multi-worker





    